/*
 * Employee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Enum of the status of an employee 
 */
@JsonAdapter(EmployeeStatusCreate.Adapter.class)
public enum EmployeeStatusCreate {
  
  ACTIVE("active"),
  
  PENDING("pending"),
  
  ON_HOLD("on_hold"),
  
  SUSPENDED("suspended"),
  
  TERMINATED("terminated"),
  
  APPLICANT("applicant"),
  
  REJECTED("rejected");

  private String value;

  EmployeeStatusCreate(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static EmployeeStatusCreate fromValue(String text) {
    for (EmployeeStatusCreate b : EmployeeStatusCreate.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<EmployeeStatusCreate> {
    @Override
    public void write(final JsonWriter jsonWriter, final EmployeeStatusCreate enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public EmployeeStatusCreate read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return EmployeeStatusCreate.fromValue(String.valueOf(value));
    }
  }
}

