/*
 * Employee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BranchSummary;
import java.io.IOException;

/**
 * Employment Type Details
 */
@ApiModel(description = "Employment Type Details")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T22:10:48.279Z")
public class EmploymentTypeDetails {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("branch")
  private BranchSummary branch = null;

  public EmploymentTypeDetails id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * ID of the employment type
   * @return id
  **/
  @ApiModelProperty(example = "1", value = "ID of the employment type")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public EmploymentTypeDetails name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of employment type
   * @return name
  **/
  @ApiModelProperty(example = "Full time", value = "Name of employment type")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public EmploymentTypeDetails branch(BranchSummary branch) {
    this.branch = branch;
    return this;
  }

   /**
   * Get branch
   * @return branch
  **/
  @ApiModelProperty(value = "")
  public BranchSummary getBranch() {
    return branch;
  }

  public void setBranch(BranchSummary branch) {
    this.branch = branch;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmploymentTypeDetails employmentTypeDetails = (EmploymentTypeDetails) o;
    return Objects.equals(this.id, employmentTypeDetails.id) &&
        Objects.equals(this.name, employmentTypeDetails.name) &&
        Objects.equals(this.branch, employmentTypeDetails.branch);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, branch);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmploymentTypeDetails {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    branch: ").append(toIndentedString(branch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

