/*
 * Employee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CostCentre;
import io.swagger.client.model.Department;
import io.swagger.client.model.EmployeeContact;
import io.swagger.client.model.EmployeeDemographics;
import io.swagger.client.model.EmployeeStatus;
import io.swagger.client.model.EmploymentType;
import io.swagger.client.model.Group;
import io.swagger.client.model.Role;
import io.swagger.client.model.Skill;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AlayaCare employee entity
 */
@ApiModel(description = "AlayaCare employee entity")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T22:10:48.279Z")
public class EmployeeDetails {
  @SerializedName("demographics")
  private EmployeeDemographics demographics = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("ac_id")
  private String acId = null;

  @SerializedName("external_id")
  private String externalId = null;

  @SerializedName("profile_id")
  private Integer profileId = null;

  @SerializedName("branch_id")
  private Integer branchId = null;

  @SerializedName("status")
  private EmployeeStatus status = null;

  @SerializedName("roles")
  private List<Role> roles = null;

  @SerializedName("groups")
  private List<Group> groups = null;

  @SerializedName("departments")
  private List<Department> departments = null;

  @SerializedName("designation")
  private String designation = null;

  @SerializedName("max_weekly_capacity")
  private String maxWeeklyCapacity = null;

  @SerializedName("min_weekly_capacity")
  private String minWeeklyCapacity = null;

  @SerializedName("username")
  private String username = null;

  @SerializedName("skills")
  private List<Skill> skills = null;

  @SerializedName("ssn_sin")
  private String ssnSin = null;

  @SerializedName("contacts")
  private List<EmployeeContact> contacts = new ArrayList<EmployeeContact>();

  @SerializedName("language")
  private String language = null;

  @SerializedName("payroll_number")
  private String payrollNumber = null;

  @SerializedName("employment_type")
  private EmploymentType employmentType = null;

  @SerializedName("cost_centre")
  private CostCentre costCentre = null;

  @SerializedName("timezone")
  private String timezone = null;

  public EmployeeDetails demographics(EmployeeDemographics demographics) {
    this.demographics = demographics;
    return this;
  }

   /**
   * Get demographics
   * @return demographics
  **/
  @ApiModelProperty(required = true, value = "")
  public EmployeeDemographics getDemographics() {
    return demographics;
  }

  public void setDemographics(EmployeeDemographics demographics) {
    this.demographics = demographics;
  }

  public EmployeeDetails id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public EmployeeDetails acId(String acId) {
    this.acId = acId;
    return this;
  }

   /**
   * AlayaCare ID for display in-app
   * @return acId
  **/
  @ApiModelProperty(example = "AC000000024", required = true, value = "AlayaCare ID for display in-app")
  public String getAcId() {
    return acId;
  }

  public void setAcId(String acId) {
    this.acId = acId;
  }

  public EmployeeDetails externalId(String externalId) {
    this.externalId = externalId;
    return this;
  }

   /**
   * Get externalId
   * @return externalId
  **/
  @ApiModelProperty(required = true, value = "")
  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  public EmployeeDetails profileId(Integer profileId) {
    this.profileId = profileId;
    return this;
  }

   /**
   * Get profileId
   * @return profileId
  **/
  @ApiModelProperty(example = "7890", value = "")
  public Integer getProfileId() {
    return profileId;
  }

  public void setProfileId(Integer profileId) {
    this.profileId = profileId;
  }

  public EmployeeDetails branchId(Integer branchId) {
    this.branchId = branchId;
    return this;
  }

   /**
   * Get branchId
   * @return branchId
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getBranchId() {
    return branchId;
  }

  public void setBranchId(Integer branchId) {
    this.branchId = branchId;
  }

  public EmployeeDetails status(EmployeeStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(required = true, value = "")
  public EmployeeStatus getStatus() {
    return status;
  }

  public void setStatus(EmployeeStatus status) {
    this.status = status;
  }

  public EmployeeDetails roles(List<Role> roles) {
    this.roles = roles;
    return this;
  }

  public EmployeeDetails addRolesItem(Role rolesItem) {
    if (this.roles == null) {
      this.roles = new ArrayList<Role>();
    }
    this.roles.add(rolesItem);
    return this;
  }

   /**
   * Employee roles
   * @return roles
  **/
  @ApiModelProperty(value = "Employee roles")
  public List<Role> getRoles() {
    return roles;
  }

  public void setRoles(List<Role> roles) {
    this.roles = roles;
  }

  public EmployeeDetails groups(List<Group> groups) {
    this.groups = groups;
    return this;
  }

  public EmployeeDetails addGroupsItem(Group groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<Group>();
    }
    this.groups.add(groupsItem);
    return this;
  }

   /**
   * Employee groups
   * @return groups
  **/
  @ApiModelProperty(value = "Employee groups")
  public List<Group> getGroups() {
    return groups;
  }

  public void setGroups(List<Group> groups) {
    this.groups = groups;
  }

  public EmployeeDetails departments(List<Department> departments) {
    this.departments = departments;
    return this;
  }

  public EmployeeDetails addDepartmentsItem(Department departmentsItem) {
    if (this.departments == null) {
      this.departments = new ArrayList<Department>();
    }
    this.departments.add(departmentsItem);
    return this;
  }

   /**
   * Employee departments
   * @return departments
  **/
  @ApiModelProperty(value = "Employee departments")
  public List<Department> getDepartments() {
    return departments;
  }

  public void setDepartments(List<Department> departments) {
    this.departments = departments;
  }

  public EmployeeDetails designation(String designation) {
    this.designation = designation;
    return this;
  }

   /**
   * Get designation
   * @return designation
  **/
  @ApiModelProperty(value = "")
  public String getDesignation() {
    return designation;
  }

  public void setDesignation(String designation) {
    this.designation = designation;
  }

  public EmployeeDetails maxWeeklyCapacity(String maxWeeklyCapacity) {
    this.maxWeeklyCapacity = maxWeeklyCapacity;
    return this;
  }

   /**
   * Get maxWeeklyCapacity
   * @return maxWeeklyCapacity
  **/
  @ApiModelProperty(example = "24.5", value = "")
  public String getMaxWeeklyCapacity() {
    return maxWeeklyCapacity;
  }

  public void setMaxWeeklyCapacity(String maxWeeklyCapacity) {
    this.maxWeeklyCapacity = maxWeeklyCapacity;
  }

  public EmployeeDetails minWeeklyCapacity(String minWeeklyCapacity) {
    this.minWeeklyCapacity = minWeeklyCapacity;
    return this;
  }

   /**
   * Get minWeeklyCapacity
   * @return minWeeklyCapacity
  **/
  @ApiModelProperty(example = "10", value = "")
  public String getMinWeeklyCapacity() {
    return minWeeklyCapacity;
  }

  public void setMinWeeklyCapacity(String minWeeklyCapacity) {
    this.minWeeklyCapacity = minWeeklyCapacity;
  }

  public EmployeeDetails username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @ApiModelProperty(value = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public EmployeeDetails skills(List<Skill> skills) {
    this.skills = skills;
    return this;
  }

  public EmployeeDetails addSkillsItem(Skill skillsItem) {
    if (this.skills == null) {
      this.skills = new ArrayList<Skill>();
    }
    this.skills.add(skillsItem);
    return this;
  }

   /**
   * List of skills associated to an employee
   * @return skills
  **/
  @ApiModelProperty(value = "List of skills associated to an employee")
  public List<Skill> getSkills() {
    return skills;
  }

  public void setSkills(List<Skill> skills) {
    this.skills = skills;
  }

  public EmployeeDetails ssnSin(String ssnSin) {
    this.ssnSin = ssnSin;
    return this;
  }

   /**
   * Social security number or Social insurance number of the employee
   * @return ssnSin
  **/
  @ApiModelProperty(example = "123456789", value = "Social security number or Social insurance number of the employee")
  public String getSsnSin() {
    return ssnSin;
  }

  public void setSsnSin(String ssnSin) {
    this.ssnSin = ssnSin;
  }

  public EmployeeDetails contacts(List<EmployeeContact> contacts) {
    this.contacts = contacts;
    return this;
  }

  public EmployeeDetails addContactsItem(EmployeeContact contactsItem) {
    this.contacts.add(contactsItem);
    return this;
  }

   /**
   * Employee contacts
   * @return contacts
  **/
  @ApiModelProperty(required = true, value = "Employee contacts")
  public List<EmployeeContact> getContacts() {
    return contacts;
  }

  public void setContacts(List<EmployeeContact> contacts) {
    this.contacts = contacts;
  }

  public EmployeeDetails language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @ApiModelProperty(example = "en", value = "")
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public EmployeeDetails payrollNumber(String payrollNumber) {
    this.payrollNumber = payrollNumber;
    return this;
  }

   /**
   * Get payrollNumber
   * @return payrollNumber
  **/
  @ApiModelProperty(example = "A123", value = "")
  public String getPayrollNumber() {
    return payrollNumber;
  }

  public void setPayrollNumber(String payrollNumber) {
    this.payrollNumber = payrollNumber;
  }

  public EmployeeDetails employmentType(EmploymentType employmentType) {
    this.employmentType = employmentType;
    return this;
  }

   /**
   * Get employmentType
   * @return employmentType
  **/
  @ApiModelProperty(value = "")
  public EmploymentType getEmploymentType() {
    return employmentType;
  }

  public void setEmploymentType(EmploymentType employmentType) {
    this.employmentType = employmentType;
  }

  public EmployeeDetails costCentre(CostCentre costCentre) {
    this.costCentre = costCentre;
    return this;
  }

   /**
   * Get costCentre
   * @return costCentre
  **/
  @ApiModelProperty(value = "")
  public CostCentre getCostCentre() {
    return costCentre;
  }

  public void setCostCentre(CostCentre costCentre) {
    this.costCentre = costCentre;
  }

  public EmployeeDetails timezone(String timezone) {
    this.timezone = timezone;
    return this;
  }

   /**
   * Timezone name in IANA format (iana.org/time-zones). If not set, returns the branch timezone. 
   * @return timezone
  **/
  @ApiModelProperty(example = "America/Toronto", value = "Timezone name in IANA format (iana.org/time-zones). If not set, returns the branch timezone. ")
  public String getTimezone() {
    return timezone;
  }

  public void setTimezone(String timezone) {
    this.timezone = timezone;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmployeeDetails employeeDetails = (EmployeeDetails) o;
    return Objects.equals(this.demographics, employeeDetails.demographics) &&
        Objects.equals(this.id, employeeDetails.id) &&
        Objects.equals(this.acId, employeeDetails.acId) &&
        Objects.equals(this.externalId, employeeDetails.externalId) &&
        Objects.equals(this.profileId, employeeDetails.profileId) &&
        Objects.equals(this.branchId, employeeDetails.branchId) &&
        Objects.equals(this.status, employeeDetails.status) &&
        Objects.equals(this.roles, employeeDetails.roles) &&
        Objects.equals(this.groups, employeeDetails.groups) &&
        Objects.equals(this.departments, employeeDetails.departments) &&
        Objects.equals(this.designation, employeeDetails.designation) &&
        Objects.equals(this.maxWeeklyCapacity, employeeDetails.maxWeeklyCapacity) &&
        Objects.equals(this.minWeeklyCapacity, employeeDetails.minWeeklyCapacity) &&
        Objects.equals(this.username, employeeDetails.username) &&
        Objects.equals(this.skills, employeeDetails.skills) &&
        Objects.equals(this.ssnSin, employeeDetails.ssnSin) &&
        Objects.equals(this.contacts, employeeDetails.contacts) &&
        Objects.equals(this.language, employeeDetails.language) &&
        Objects.equals(this.payrollNumber, employeeDetails.payrollNumber) &&
        Objects.equals(this.employmentType, employeeDetails.employmentType) &&
        Objects.equals(this.costCentre, employeeDetails.costCentre) &&
        Objects.equals(this.timezone, employeeDetails.timezone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(demographics, id, acId, externalId, profileId, branchId, status, roles, groups, departments, designation, maxWeeklyCapacity, minWeeklyCapacity, username, skills, ssnSin, contacts, language, payrollNumber, employmentType, costCentre, timezone);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmployeeDetails {\n");
    
    sb.append("    demographics: ").append(toIndentedString(demographics)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    acId: ").append(toIndentedString(acId)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    profileId: ").append(toIndentedString(profileId)).append("\n");
    sb.append("    branchId: ").append(toIndentedString(branchId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("    departments: ").append(toIndentedString(departments)).append("\n");
    sb.append("    designation: ").append(toIndentedString(designation)).append("\n");
    sb.append("    maxWeeklyCapacity: ").append(toIndentedString(maxWeeklyCapacity)).append("\n");
    sb.append("    minWeeklyCapacity: ").append(toIndentedString(minWeeklyCapacity)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    skills: ").append(toIndentedString(skills)).append("\n");
    sb.append("    ssnSin: ").append(toIndentedString(ssnSin)).append("\n");
    sb.append("    contacts: ").append(toIndentedString(contacts)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    payrollNumber: ").append(toIndentedString(payrollNumber)).append("\n");
    sb.append("    employmentType: ").append(toIndentedString(employmentType)).append("\n");
    sb.append("    costCentre: ").append(toIndentedString(costCentre)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

