/*
 * Employee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.EmployeeDetails;
import io.swagger.client.model.EmployeeUpdate;
import io.swagger.client.model.ErrorResponse;
import io.swagger.client.model.SuccessResponse;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EmployeesApi
 */
@Ignore
public class EmployeesApiTest {

    private final EmployeesApi api = new EmployeesApi();

    
    /**
     * Get employee by ID
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void employeesEmployeeIdGetTest() throws Exception {
        String employeeId = null;
        EmployeeDetails response = api.employeesEmployeeIdGet(employeeId);

        // TODO: test validations
    }
    
    /**
     * Create/Modify employee
     *
     * Create/Modify employee
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void employeesEmployeeIdPutTest() throws Exception {
        String employeeId = null;
        EmployeeUpdate body = null;
        SuccessResponse response = api.employeesEmployeeIdPut(employeeId, body);

        // TODO: test validations
    }
    
    /**
     * Get all employees
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void employeesGetTest() throws Exception {
        EmployeeDetails response = api.employeesGet();

        // TODO: test validations
    }
    
}
